name: Continuous Integration

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 18 environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'
      - run: npm ci
      - run: npm test
      - run: CCL_TREEISH=$(git rev-parse --short HEAD) npm run build
      - uses: richardsimko/update-tag@v1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: latest
          tag_name: latest
          files: |
            dist/**/*
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 3

  test-android:
    uses: ./.github/workflows/reusable-ccl-test-android.yml
    secrets: inherit
    needs:
      - build

  test-ios:
    uses: ./.github/workflows/reusable-ccl-test-ios.yml
    secrets: inherit
    needs:
      - build