name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm test
      - run: CCL_VERSION=$(echo $GITHUB_REF_NAME) CCL_TREEISH=$(git rev-parse --short HEAD) npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 3

  test-android:
    uses: ./.github/workflows/reusable-ccl-test-android.yml
    secrets: inherit
    needs:
      - build

  test-ios:
    uses: ./.github/workflows/reusable-ccl-test-ios.yml
    secrets: inherit
    needs:
      - build

  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - test-android
      - test-ios
    steps:
      - name: Download artifacts from jobs
        uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(env.GITHUB_REF_NAME, '-rc.') }}
          name: ${{ env.GITHUB_REF_NAME }}
          tag_name: ${{ env.GITHUB_REF_NAME }}
          files: dist/*
          generate_release_notes: true