name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm test
      - run: CCL_VERSION=$(echo $GITHUB_REF_NAME) npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(env.GITHUB_REF_NAME, '-rc.') }}
          name: ${{ env.GITHUB_REF_NAME }}
          tag_name: ${{ env.GITHUB_REF_NAME }}
          files: dist/*